import logging
from fastapi import APIRouter, HTTPException, UploadFile, File, Form
import base64

from app.schemas import ChatRequest
from app.services.chat_service import ChatService
from app.services.media_service import MediaService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api")

import re

def format_chat_response(response_text: str, extra_fields: dict = None):
    """
    Summary: Formats the AI's raw Markdown response into a structured JSON dictionary for the frontend.
    
    Flow:
    1. Uses a regular expression to locate any Markdown image tags (![alt](url)) within the AI's response text.
    2. Cleans the response text by completely removing the matched image tags, leaving only clean conversational text.
    3. Normalizes line breaks to prevent excessive whitespace caused by removing the images.
    4. Constructs a dictionary containing the clean reply, a boolean indicating if images are present, and a list of extracted image URLs.
    5. Optionally merges any additional metadata (e.g., audio transcripts or vision text) from the extra_fields dictionary into the final response object.
    
    Args:
        response_text (str): The raw text response generated by the AI assistant, potentially containing markdown image tags.
        extra_fields (dict, optional): Additional key-value pairs to merge into the final response payload. Defaults to None.
        
    Returns:
        dict: A structured dictionary containing 'reply', 'has_image', 'image_urls', 'first_image_url', and any extra_fields.
    """
    # Regex to match Markdown images: ![alt](url)
    pattern = r'!\[.*?\]\((.*?)\)'
    urls = re.findall(pattern, response_text)
    
    # Clean up the text by removing the image markdown (so it can be used as a clean caption)
    clean_text = re.sub(pattern, '', response_text).strip()
    # Clean up any excessive newlines left behind
    clean_text = re.sub(r'\n{3,}', '\n\n', clean_text)
    
    response_data = {
        "reply": clean_text,
        "has_image": len(urls) > 0,
        "image_urls": urls,
        "first_image_url": urls[0] if urls else None
    }
    
    # Merge any extra fields (like transcripts)
    if extra_fields:
        response_data.update(extra_fields)
        
    return response_data

@router.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """
    Summary: Handles standard text-based chat requests from the frontend client.
    
    Flow:
    1. Receives a validated ChatRequest JSON payload containing the user's message and their unique session_id.
    2. Delegates the core processing logic to ChatService.process_standard_chat(), passing the session ID and user message.
    3. The ChatService coordinates fetching memory, querying the AI, and determining upsells, returning a raw text response.
    4. Passes the raw text response into format_chat_response() to extract embedded images and structure the final JSON output.
    5. In the event of an exception anywhere in the pipeline, logs the error and safely returns a generic user-friendly error message.
    
    Args:
        request (ChatRequest): A Pydantic schema containing the 'session_id' (str) and the 'message' (str) from the user.
        
    Returns:
        dict: The formatted response payload containing the AI's reply and any parsed image data.
    """
    try:
        logger.info(f"Received chat request for session {request.session_id}")
        
        # Delegate processing to the ChatService
        response_text = await ChatService.process_standard_chat(request.session_id, request.message)
        
        # Return structured data for frontend
        return format_chat_response(response_text)
        
    except Exception as general_error:
        logger.error(f"Unexpected error in chat_endpoint: {general_error}", exc_info=True)
        return {"reply": "I'm experiencing a temporary technical issue. Please try again in a moment.", "has_image": False}

@router.post("/chat/audio")
async def chat_audio_endpoint(session_id: str = Form(...), file: UploadFile = File(...)):
    """
    Summary: Processes voice note uploads by transcribing them to text before querying the AI assistant.
    
    Flow:
    1. Receives an audio file (e.g., MP3/WAV) and the user's session_id as multipart form data.
    2. Reads the audio file's binary data into memory.
    3. Delegates to MediaService.process_audio_deepgram() to call the Deepgram API and retrieve the transcribed text.
    4. Validates the transcript; if empty, returns an error message asking the user to try again.
    5. Modifies the user's prompt to explicitly instruct the AI that the input is a transcribed voice note, asking it to extract product intents.
    6. Passes the modified prompt to ChatService.process_standard_chat() for standard agent execution.
    7. Formats the AI's response, attaching the original transcript to the extra_fields so the frontend can display it.
    
    Args:
        session_id (str): The unique identifier for the user's session, submitted as a form field.
        file (UploadFile): The uploaded audio file object containing the voice note.
        
    Returns:
        dict: The formatted response payload containing the AI's reply, image data, and the raw audio transcript.
    """
    try:
        logger.info(f"Received audio chat request for session {session_id}")
        
        audio_bytes = await file.read()
        transcript = await MediaService.process_audio_deepgram(audio_bytes)
        
        if not transcript:
            return {"reply": "Sorry, I couldn't understand the audio. Please try speaking clearly or typing instead.", "has_image": False}
            
        modified_message = (
            f"Transcribed Audio: {transcript}\n\n"
            f"User is looking for product name recovered from this text."
        )
        
        response_text = await ChatService.process_standard_chat(session_id, modified_message)
        
        return format_chat_response(response_text, {"transcript": transcript})
        
    except Exception as general_error:
        logger.error(f"Unexpected error in chat_audio_endpoint: {general_error}", exc_info=True)
        return {"reply": "I'm experiencing a temporary technical issue with audio processing. Please try again.", "has_image": False}


@router.post("/chat/image")
async def chat_image_endpoint(session_id: str = Form(...), file: UploadFile = File(...)):
    """
    Summary: Processes image uploads by using a vision model to extract text before querying the AI assistant.
    
    Flow:
    1. Receives an image file (e.g., JPG/PNG) and the user's session_id as multipart form data.
    2. Reads the image binary data into memory and encodes it into a Base64 string for API transmission.
    3. Delegates to MediaService.process_image_vision(), which calls Azure OpenAI GPT-4 Vision to analyze the image and extract legible text.
    4. Validates the extracted text; if the vision model found no text, returns an error message requesting a clearer image.
    5. Constructs a modified prompt instructing the AI that the provided text was extracted from an image, asking it to identify the product.
    6. Routes this modified prompt through the standard ChatService.process_standard_chat() pipeline.
    7. Formats the final AI response, attaching the extracted text to the extra_fields for frontend display or debugging.
    
    Args:
        session_id (str): The unique identifier for the user's session, submitted as a form field.
        file (UploadFile): The uploaded image file object to be analyzed.
        
    Returns:
        dict: The formatted response payload containing the AI's reply, recommended product images, and the text extracted by the vision model.
    """
    try:
        logger.info(f"Received image chat request for session {session_id}")
        
        image_bytes = await file.read()
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')
        
        extracted_text = await MediaService.process_image_vision(image_base64)
        
        if not extracted_text:
            return {"reply": "Sorry, I couldn't extract any text from that image. Make sure it's clear and well-lit.", "has_image": False}
            
        modified_message = (
            f"Text extracted from image: {extracted_text}\n\n"
            f"User is looking for product name recovered from this text."
        )
        
        response_text = await ChatService.process_standard_chat(session_id, modified_message)
        
        return format_chat_response(response_text, {"extracted_text": extracted_text})
        
    except Exception as general_error:
        logger.error(f"Unexpected error in chat_image_endpoint: {general_error}", exc_info=True)
        return {"reply": "I'm experiencing a temporary technical issue with image processing. Please try again.", "has_image": False}
